### ISSUE TITLE
Getting "class file for androidx.appcompat.app.AppCompatActivity not found" while building

### ISSUE THREAD

**Issue by Ajax-ua** [stewwan/capacitor-fcm#32]
I'm getting an error while building the app in Android Studio:
```
.../node_modules/capacitor-fcm/android/capacitor-fcm/src/main/java/io/stewan/capacitor/fcm/FCMPlugin.java:96: error: cannot access AppCompatActivity
        FirebaseInstanceId.getInstance().getInstanceId().addOnSuccessListener(getActivity(),  new OnSuccessListener<InstanceIdResult>() {
                                                                                         ^
  class file for androidx.appcompat.app.AppCompatActivity not found
```

I'm using @capacitor/core v 2.0.0 and @capacitor/android v 2.0.0

**Comment by savgiannis** [comment]
I have the same issue too, it seems it does not work with the new capacitor 2.0.0 version due to the fact it uses Android X

**Comment by stewwan** [comment]
capacitor-fcm 2+ is for capacitor v2. y'all gotta need to refactor your apps

**Comment by Ajax-ua** [comment]
@stewwan I was using capacitor-fcm v 2.0.0 when I've faced this problem. So it's the problem of the latest version

**Comment by stewwan** [comment]
can you set up a reproducible example?

**Comment by Ajax-ua** [comment]
Removing and adding Android platform has solved the issue. Thanks

**Comment by stewwan** [comment]
FWIW I've just faced the same issue

to fix it add this to your app gradle.properties

```
android.useAndroidX=true
android.enableJetifier=true
```

clean project + rebuild in Android Studio

**Comment by Vicviral** [comment]
Hi guys. How do I go about this.

Cannot access 'android.app.Activity' which is a supertype of 'com.example.nextbook.MainActivity'. Check your module classpath for missing or conflicting dependencies
